#!/bin/bash
#
# Coder workspace bootstrap. This runs on every workspace start, not just the
# first one, so it is split into two halves:
#
#   provision_once  expensive/network-heavy setup (apt, brew, omz, npm). Guarded
#                   by ~/.dotfiles-installed. $HOME is a persistent NFS volume on
#                   CoreWeave, so the marker survives restarts and this really
#                   does run once per workspace.
#   sync_config     cheap, idempotent config sync. Runs every time, so fixes to
#                   this repo reach existing workspaces on their next restart.
#
# Everything in sync_config must be safe to re-run, and must not clobber state
# that other installers or the user own. Two specific traps, both hit in
# practice: safe-chain appends its own block to ~/.zshrc *after* this script
# runs, and Claude Code writes user settings into ~/.claude/settings.json. A
# blind `cp` over either file silently destroys that. Hence the managed-block
# merge for ~/.zshrc and the create-if-absent handling for settings.json.

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANAGED_BEGIN="# >>> coder-dotfiles managed block - regenerated by install.sh, edits here are lost >>>"
MANAGED_END="# <<< coder-dotfiles managed block <<<"

log() { printf '[dotfiles] %s\n' "$*"; }

# Copy src over dst only if they differ, keeping one backup of what was there.
sync_file() {
  local src="$1" dst="$2"
  if cmp -s "$src" "$dst"; then
    return 0
  fi
  if [ -e "$dst" ]; then
    cp -p "$dst" "$dst.bak"
    log "backed up $dst -> $dst.bak"
  fi
  mkdir -p "$(dirname "$dst")"
  cp "$src" "$dst"
  log "updated $dst"
}

# Install this repo's zshrc as a delimited block at the top of ~/.zshrc, leaving
# anything outside the block alone. Later appenders (safe-chain, nvm, rustup,
# hand edits) therefore survive every subsequent sync.
sync_zshrc() {
  local shipped="$DOTFILES_DIR/zshrc"
  local block merged foreign
  block="$(mktemp)"
  {
    printf '%s\n' "$MANAGED_BEGIN"
    cat "$shipped"
    printf '%s\n' "$MANAGED_END"
  } >"$block"

  if [ ! -e "$HOME/.zshrc" ]; then
    mv "$block" "$HOME/.zshrc"
    log "created ~/.zshrc"
    return
  fi

  if grep -qF "$MANAGED_BEGIN" "$HOME/.zshrc"; then
    merged="$(mktemp)"
    awk -v begin="$MANAGED_BEGIN" -v end="$MANAGED_END" -v blockfile="$block" '
      $0 == begin { inblock = 1; while ((getline line < blockfile) > 0) print line; close(blockfile); next }
      $0 == end   { inblock = 0; next }
      !inblock    { print }
    ' "$HOME/.zshrc" >"$merged"
    if cmp -s "$merged" "$HOME/.zshrc"; then
      log "~/.zshrc already up to date"
    else
      cp -p "$HOME/.zshrc" "$HOME/.zshrc.bak"
      cat "$merged" >"$HOME/.zshrc"
      log "refreshed managed block in ~/.zshrc (backup: ~/.zshrc.bak)"
    fi
    rm -f "$block" "$merged"
    return
  fi

  # First run against a workspace whose ~/.zshrc predates the managed block. It
  # is a copy of some older shipped zshrc plus whatever was appended after it, so
  # treat any line that is not verbatim in the shipped file as a local addition
  # and re-attach it below the block. Comments and blanks are dropped rather than
  # carried over: reworded comments in the shipped file would otherwise show up as
  # duplicated cruft, and ~/.zshrc.bak still has the verbatim original.
  foreign="$(awk '
    NR == FNR { shipped[$0] = 1; next }
    /^[[:space:]]*(#|$)/ { next }
    !($0 in shipped) { print }
  ' "$shipped" "$HOME/.zshrc")"
  cp -p "$HOME/.zshrc" "$HOME/.zshrc.bak"
  {
    cat "$block"
    if [ -n "$foreign" ]; then
      printf '\n# --- local additions carried over from the pre-managed ~/.zshrc ---\n'
      printf '%s\n' "$foreign"
    fi
  } >"$HOME/.zshrc"
  rm -f "$block"
  log "adopted ~/.zshrc into a managed block (backup: ~/.zshrc.bak)"
  if [ -n "$foreign" ]; then
    log "carried over $(printf '%s\n' "$foreign" | grep -c .) non-shipped line(s) - worth an eyeball:"
    printf '%s\n' "$foreign" | sed 's/^/[dotfiles]     /'
  fi
}

sync_config() {
  sync_file "$DOTFILES_DIR/gitconfig" "$HOME/.gitconfig"
  sync_zshrc

  # A bare `compinit` in the old zshrc wrote this dump with a file count that
  # never matched again, forcing a full fpath rescan (~13s over NFS) in every new
  # shell. Nothing reads it now. Leave oh-my-zsh's own
  # ~/.zcompdump-<host>-<version>[.zwc] alone: deleting that just makes the next
  # shell rebuild it.
  if [ -f "$HOME/.zcompdump" ]; then
    rm -f "$HOME/.zcompdump"
    log "removed stale ~/.zcompdump"
  fi

  # Ensure zsh starts even if chsh doesn't stick (e.g. containers).
  # Login shells (SSH, tmux) source ~/.profile; interactive non-login shells
  # source ~/.bashrc -- so install the hand-off into both. The $- guard means
  # non-interactive shells (e.g. `ssh host cmd`) are never replaced.
  local rc
  for rc in "$HOME/.profile" "$HOME/.bashrc"; do
    grep -qF "exec zsh" "$rc" 2>/dev/null || cat >>"$rc" <<'RCEOF'

# Switch to zsh for interactive shells
case $- in
  *i*) [ -z "$ZSH_VERSION" ] && [ -x "$(command -v zsh)" ] && exec zsh ;;
esac
RCEOF
  done

  # Allow pip to install packages system-wide (workaround for PEP 668)
  local pip_conf
  for pip_conf in /etc/pip.conf "$HOME/.config/pip/pip.conf"; do
    mkdir -p "$(dirname "$pip_conf")"
    cat >"$pip_conf" <<'PIPEOF'
[global]
break-system-packages = true
PIPEOF
  done

  # Create-if-absent only: Claude Code owns this file at runtime (theme, tui,
  # permissions, ...), so overwriting it on every start would discard settings.
  mkdir -p "$HOME/.claude"
  if [ ! -f "$HOME/.claude/settings.json" ]; then
    cat >"$HOME/.claude/settings.json" <<'EOF'
{
  "env": {
    "ENABLE_LSP_TOOL": "1"
  },
  "enabledPlugins": {
    "pyright-lsp@claude-plugins-official": true
  }
}
EOF
    log "created ~/.claude/settings.json"
  fi
}

provision_once() {
  # Zsh Shell
  add-apt-repository -y ppa:git-core/ppa
  apt -y update && apt -y upgrade
  apt -y install build-essential \
                  curl git xclip htop tree nano
  apt install -y zsh
  sudo chsh -s /usr/bin/zsh "$(whoami)"

  # Oh My Zsh installation. Its installer writes its own ~/.zshrc; sync_config
  # runs afterwards and replaces that with the managed block.
  echo "Y" | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  # brew (activate for remainder of this script)
  test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
  test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  if command -v brew >/dev/null 2>&1; then
    BREW_SHELLENV="eval \"\$($(brew --prefix)/bin/brew shellenv)\""
    grep -qF "brew shellenv" ~/.bashrc 2>/dev/null || echo "$BREW_SHELLENV" >>~/.bashrc

    brew install docker
    brew install k9s
    brew install node
  else
    log "brew not found; skipped docker/k9s/node"
  fi

  # Claude Code
  curl -fsSL https://claude.ai/install.sh | bash

  # Python LSP for Claude Code
  npm install -g pyright
}

if [ -f "$HOME/.dotfiles-installed" ]; then
  log "already provisioned; syncing config only"
else
  log "first run: provisioning workspace"
  provision_once
fi

# Always last, so it wins over anything the installers above wrote.
sync_config

# Plugin commands are cheap no-ops once installed, but need the claude binary.
if command -v claude >/dev/null 2>&1; then
  claude plugin marketplace update claude-plugins-official || true
  claude plugin install pyright-lsp || true
  claude plugin enable pyright-lsp || true
fi

# Mark provisioning as complete
touch "$HOME/.dotfiles-installed"
